### ISSUE TITLE
Occasional "no implicit conversion of nil into String (TypeError)" when calling buckets.find

### ISSUE THREAD

**Issue by lencioni** [qoobaa/s3#107]
I am occasionally seeing "no implicit conversion of nil into String (TypeError)" when calling `buckets.find`.

Here's the relevant bit of the stack trace:

```
/var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/s3-0.3.23/lib/s3/signature.rb:139:in `digest': no implicit conversion of nil into String (TypeError)
	from /var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/s3-0.3.23/lib/s3/signature.rb:139:in `canonicalized_signature'
	from /var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/s3-0.3.23/lib/s3/signature.rb:32:in `generate'
	from /var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/s3-0.3.23/lib/s3/connection.rb:188:in `block in send_request'
	from /var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:853:in `start'
	from /var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/s3-0.3.23/lib/s3/connection.rb:177:in `send_request'
	from /var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/s3-0.3.23/lib/s3/connection.rb:88:in `request'
	from /var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/s3-0.3.23/lib/s3/service.rb:77:in `service_request'
	from /var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/s3-0.3.23/lib/s3/bucket.rb:209:in `bucket_request'
	from /var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/s3-0.3.23/lib/s3/bucket.rb:171:in `bucket_headers'
	from /var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/s3-0.3.23/lib/s3/bucket.rb:16:in `retrieve'
	from /var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/s3-0.3.23/lib/s3/buckets_extension.rb:12:in `find_first'
	from /var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/likadan-6e4a1e0fef94/lib/likadan_uploader.rb:46:in `find_or_build_bucket'
```

and here you can see the line of code that calls `find`: https://github.com/lencioni/likadan/blob/6e4a1e0f/lib/likadan_uploader.rb#L46

Here is the line that is erroring out: https://github.com/qoobaa/s3/blob/99fad2ae/lib/s3/signature.rb#L139

Any thoughts?

**Comment by lencioni** [comment]
Hmm, perhaps our `secret_access_key` is occasionally `nil` for some reason?

**Comment by lencioni** [comment]
blarf, yeah, this seems to have been a configuration glitch. Perhaps it would be useful to add a helpful message if these things aren't set properly?

**Comment by qoobaa** [comment]
Could you create a PR adding a better error message?

**Comment by lencioni** [comment]
Sure!
