### ISSUE TITLE
S3::Error::RequestTimeout: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.

### ISSUE THREAD

**Issue by naquad** [qoobaa/s3#65]
Hi.

I'm trying to upload an image to my bucket. Thats my code:

<pre><code>
require 's3'

service = S3::Service.new(access_key_id: 'xxxxx', secret_access_key: 'xxxxx')
service.buckets # returns me correct list of my buckets so connection is established and works ok
obj = service.buckets.first.objects.build('1.jpg') # now create an object
obj.content = open('1.jpg', 'rb', encoding: 'BINARY') # file i want to upload
obj.save # save it
</code></pre>

result is:

<pre><code>
/usr/lib/ruby/gems/1.9.1/gems/s3-0.3.11/lib/s3/connection.rb:217:in `handle_response': Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed. (S3::Error::RequestTimeout)
    from /usr/lib/ruby/gems/1.9.1/gems/s3-0.3.11/lib/s3/connection.rb:204:in `send_request'
    from /usr/lib/ruby/gems/1.9.1/gems/s3-0.3.11/lib/s3/connection.rb:201:in `send_request'
    from /usr/lib/ruby/gems/1.9.1/gems/s3-0.3.11/lib/s3/connection.rb:89:in `request'
    from /usr/lib/ruby/gems/1.9.1/gems/s3-0.3.11/lib/s3/service.rb:74:in `service_request'
    from /usr/lib/ruby/gems/1.9.1/gems/s3-0.3.11/lib/s3/bucket.rb:171:in `bucket_request'
    from /usr/lib/ruby/gems/1.9.1/gems/s3-0.3.11/lib/s3/object.rb:207:in `object_request'
    from /usr/lib/ruby/gems/1.9.1/gems/s3-0.3.11/lib/s3/object.rb:189:in `put_object'
    from /usr/lib/ruby/gems/1.9.1/gems/s3-0.3.11/lib/s3/object.rb:83:in `save'
    from test.rb:8:in `<main>'
</code></pre>

I'm following your guide and and everything except upload works :( My ruby version is 1.9.3 btw.

**Comment by IanVaughan** [comment]
```
require "s3"

service = S3::Service.new(
  :access_key_id     => ENV['ACCESS_KEY_ID'],
  :secret_access_key => ENV['SECRET_ACCESS_KEY']
)

bucket_name = ENV['BUCKET_NAME']
file = ENV['FILENAME']

bucket = service.buckets.find(bucket_name)

object = bucket.objects.build(file)
object.content = open(file)
object.save
```

**Comment by mauriciofloresl** [comment]
Reading over here https://github.com/aws/aws-sdk-js/issues/281 it seems it's an issue with the content-length.
